[package]
name = "rt-weekend-multithreaded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
glam = "0.23.0"
image = "0.24.6"
itertools = "0.10.5"
rayon = "1.7.0"
